### ISSUE TITLE
Text color / light mode

### ISSUE THREAD

**Issue by martin-ro** [pxlrbt/filament-environment-indicator#1]
If you don't use the dark mode for Filament the button color is dark/black. That doesn't look too good. 

Maybe configure text color separate? If you would accept a PR I will have another look when I got time.

Cheers

**Comment by pxlrbt** [comment]
Sorry, didn't think about the light mode 🙈 Happy to accept a PR.

**Comment by pxlrbt** [comment]
I'll reopen this, until we have a solution for it.

**Comment by martin-ro** [comment]
Here's  the  PR: #2

**Comment by pxlrbt** [comment]
Thanks. Will have a look at it after the weekend

**Comment by pxlrbt** [comment]
Closed by #2
