### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by mcfaith9** [pxlrbt/filament-environment-indicator#7]
I tried to use it on my `AppServiceProvider`

```
FilamentEnvironmentIndicator::configureUsing(function (FilamentEnvironmentIndicator $indicator) {
            $indicator->showBadge = fn () => false;
            $indicator->showBorder = fn () => true;
        }, isImportant: true);
```

and its says Class `"App\Providers\pxlrbt\FilamentEnvironmentIndicator" not found`

**Comment by pxlrbt** [comment]
You didn't import the correct class `pxlrbt\FilamentEnvironmentIndicator\FilamentEnvironmentIndicator`. This is basic PHP and therefore wasn't documented on the repo.
